Repository OWASP/CheatSheetSeries, pull requests merged in 2019-10, with the labels that each got.

#228 Update new cheatsheet template. Fixes #222
  templates/New_CheatSheet.md
Labels: INTERNAL

#249 Grammar fixes on readme.md file
  README.md
Labels: HacktoberFest

#268 general copy-editing
  cheatsheets/Error_Handling_Cheat_Sheet.md
Labels: WAITING_UPDATE

#219 New cheat sheet: Node.js Security Cheat Sheet
  cheatsheets/Nodejs_security_cheat_sheet.md
Labels: HacktoberFest

#231 Add unsolicited response section and update encryption section.
  cheatsheets/SAML_Security_Cheat_Sheet.md
Labels: HacktoberFest
