Repository OWASP/CheatSheetSeries, pull requests merged in 2019-11, with the labels that each got.

#223 Create new CS for multifactor authentication (MFA)
  cheatsheets/Multifactor_Authentication_Cheat_Sheet.md
Labels: NEW_CS

#288 Update the issue templates
  .github/ISSUE_TEMPLATE/new_cheatsheet_proposal.md
  .github/ISSUE_TEMPLATE/update_cheatsheet_proposal.md
Labels: INTERNAL

#290 Add Awesome Node.js Security resources
  cheatsheets/Nodejs_security_cheat_sheet.md
Labels: UPDATE_CS

#292 Fix issue templates
  .github/ISSUE_TEMPLATE/new_cheatsheet_proposal.md
Labels: INTERNAL

#295 Feat: GH Actions MD Linter
  .github/workflows/md_lint_check.yml
  .travis.yml
  package.json
  scripts/Apply_Linter_Check.sh
Labels: INTERNAL
