Repository OWASP/CheatSheetSeries, pull requests merged in 2019-12, with the labels that each got.

#311 Add new resource to additional reading in JWT CS
  cheatsheets/JSON_Web_Token_Cheat_Sheet_for_Java.md
Labels: UPDATE_CS

#250 Added python section
  cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md
Labels: HacktoberFest

#327 Create some style guidelines
  CONTRIBUTING.md
Labels: INTERNAL
